[project]
name = "holon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.65",
    "dotenv>=0.9.9",
    "gql[all]>=4.0.0",
    "graphene>=3.4.3",
    "requests>=2.32.5",
]
